context('P')

test_that('P', {
  MLAK:::.onLoad()
  
  w = P(c(1:8, NA, NA), 1, FALSE)
  expect_equal(w, 10)
  w = P(c(1:8, NA, NA), 1:3, FALSE)
  expect_equal(w, 30)
  w = P(c(1:8, NA, NA), 1, FALSE, znakProcent = TRUE)
  expect_equal(w, '10%')
  w = P(c(1:8, NA, NA), 1)
  expect_equal(w, '                   10.0%')
  w = P(c(1:8, NA, NA), 1:3, dokl = 0)
  expect_equal(w, '                                 30%')
  
  w = P(c(1:7, NA, NA), 1:3, FALSE, 2)
  expect_equal(w, 33.33)
  w = P(c(1:7, NA, NA), 1:3, FALSE, 1, FALSE)
  expect_equal(w, 33.3)
  w = P((1:10)[rep(F, 10)], 1:3, FALSE)
  expect_equal(w, NA_real_)
  w = P((1:10)[rep(F, 10)], 1:3)
  expect_equal(w, '                            -%')
})

test_that('Pw', {
  MLAK:::.onLoad()
  
  w = Pw(c(1:8, NA, NA), 1, FALSE)
  expect_equal(w, 12.5)
  w = Pw(c(1:8, NA, NA), 1, FALSE, znakProcent = TRUE)
  expect_equal(w, '12.5%')
  w = Pw(c(1:8, NA, NA), 1:3, FALSE)
  expect_equal(w, 37.5)
  w = Pw(c(1:8, NA, NA), 1:3, FALSE, 0)
  expect_equal(w, 38)
  w = Pw(c(1:8, NA, NA), 1:3, FALSE, 0, znakProcent = TRUE)
  expect_equal(w, '38%')
  w = Pw(c(1:8, NA, NA), 1:3, FALSE, 2, FALSE)
  expect_equal(w, 37.5)
  w = Pw((1:10)[rep(F, 10)], 1:3, FALSE)
  expect_equal(w, NA_real_)
  w = Pw((1:10)[rep(F, 10)], 1:3, FALSE, znakProcent = TRUE)
  expect_equal(w, '-%')
})
